// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZ8KEFs82Y2WmAe0kKyqYyCSZXAfNTEc',
    appId: '1:459040907750:web:1b85e95c75a0ceabdab627',
    messagingSenderId: '459040907750',
    projectId: 'signup-page-urbanroots',
    authDomain: 'signup-page-urbanroots.firebaseapp.com',
    databaseURL: 'https://signup-page-urbanroots-default-rtdb.firebaseio.com',
    storageBucket: 'signup-page-urbanroots.firebasestorage.app',
    measurementId: 'G-NQ8SMVB5X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlruXK8t3AZuqlmdQxdSQdxORkNIQ-qc',
    appId: '1:459040907750:android:5864ce949b4eb7bedab627',
    messagingSenderId: '459040907750',
    projectId: 'signup-page-urbanroots',
    databaseURL: 'https://signup-page-urbanroots-default-rtdb.firebaseio.com',
    storageBucket: 'signup-page-urbanroots.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTaiVOdlq6KLumzvpYJtCH_g0mY3JbGk',
    appId: '1:459040907750:ios:9436e0693760ab7adab627',
    messagingSenderId: '459040907750',
    projectId: 'signup-page-urbanroots',
    databaseURL: 'https://signup-page-urbanroots-default-rtdb.firebaseio.com',
    storageBucket: 'signup-page-urbanroots.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfTaiVOdlq6KLumzvpYJtCH_g0mY3JbGk',
    appId: '1:459040907750:ios:9436e0693760ab7adab627',
    messagingSenderId: '459040907750',
    projectId: 'signup-page-urbanroots',
    databaseURL: 'https://signup-page-urbanroots-default-rtdb.firebaseio.com',
    storageBucket: 'signup-page-urbanroots.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZ8KEFs82Y2WmAe0kKyqYyCSZXAfNTEc',
    appId: '1:459040907750:web:7265e786ccd698f7dab627',
    messagingSenderId: '459040907750',
    projectId: 'signup-page-urbanroots',
    authDomain: 'signup-page-urbanroots.firebaseapp.com',
    databaseURL: 'https://signup-page-urbanroots-default-rtdb.firebaseio.com',
    storageBucket: 'signup-page-urbanroots.firebasestorage.app',
    measurementId: 'G-YZ12TTZC19',
  );
}
