name: mobile_app
description: "UrbanRoots Smart Garden Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core & State Management
  provider: ^6.1.2     
  shared_preferences: ^2.3.0
  
  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  font_awesome_flutter: ^10.6.0
  lucide_icons: 0.257.0
  lottie: ^3.3.2
  
  # Networking, Files & Core APIs
  http: ^1.6.0
  payhere_mobilesdk_flutter: ^3.2.2
  vibration: ^3.1.8
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  image_picker: ^1.2.1
  pdf: ^3.10.8
  printing: ^5.12.0
  js: ^0.6.7
  intl: ^0.19.0
  geolocator: ^14.0.2
  
  # Backend: Firebase & Supabase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.0.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Plants/flowers/
    - assets/images/Plants/Fruits/
    - assets/images/Plants/Kitchen Essentials/
    - assets/animations/
    - assets/animations/pet_idle.json
    - assets/animations/pet_happy.json
    - assets/animations/pet_sad.json

  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700